### PR TITLE
Implement closed-by-default email list. #54

### PR DESCRIPTION
**Pull request by synox**

### CODE REVIEW

**Comment by synox** [comment]
Good point about the mouse pointer. I'll make it as a link. 

I removed autorefresh and added notification. Those features are hard to combine.

**Comment by bertlio** [comment]
I've just tried the new codes but I'm not getting any notifications for new emails? and no new emails are appearing... Could you please help to troubleshoot? Thanks!

**Comment by synox** [comment]
Please add the link to a demo to troubleshoot.

**Comment by synox** [comment]
Ps: it should reload automatically if there are no mails.

**Comment by ParveenBhadooOfficial** [comment]
Troubleshoot at https://bhadoomail.com , No notification for new email. also for no auto refresh when new mail arrives.

**Comment by synox** [comment]
The api should retun 0, but returns empty page:

https://m.bhadoomail.com/json-api.php?action=has_new_messages&address=nerciert91@bhadoomail.com&email_ids=

Do you have php errors in the log?

**Comment by bertlio** [comment]
Hi synox, I confirm getting the same issues as Parveen!
and the api is returning a blank page...

[Fri Jun 15 05:51:17 2018] [warn] [client 23.247.123.2] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required '../../config.php' (include_path='.:') in /home/user/website.com/json-api.php on line 3, referer: https://www.website.com/?demo@website.com

Seems that it's not fetching the correct path for the config.php ('../../config.php')

**Comment by bertlio** [comment]
Setting the correct path in the json-api.php works great! 
Everything looks perfect now... Thanks for the smart implementation synox!

**Comment by bertlio** [comment]
One last thing please... How can I override the css for the notification alert, I want to change the background color and text color of the notification? I tried but it's not working...

**Comment by synox** [comment]
Thank you @bertlio  for finding the Problem. I updated the README. 

See the background color options at https://getbootstrap.com/docs/4.0/components/alerts/. 
Which color would you like?

**Comment by synox** [comment]
I added cursor pointer, but don't know how to style it better.

**Comment by bertlio** [comment]
That's fantastic @synox ! 
Thanks for the background color options, I was able to find one color combo to my likings ;-)
The new functionalities, timings and cursor pointer are just perfect! You're great!!!

**Comment by ParveenBhadooOfficial** [comment]
@synox Works Great Now.

**Pull request merged**
