### PR TITLE
Feature/refactor imap client

### PR DESCRIPTION
**Pull request by synox**
goal: more OO, no if-else

https://www.refactoring.com/catalog/replaceConditionalWithVisitor.html
https://francescocirillo.com/pages/anti-if-campaign
https://www.refactoring.com/catalog/replaceConditionalWithPolymorphism.html
http://michaelfeathers.typepad.com/michael_feathers_blog/2013/11/unconditional-programming.html
https://haacked.com/archive/2013/11/08/death-to-the-if-statement.aspx/

### CODE REVIEW

**Comment by synox** [comment]
@ParveenBhadooOfficial @Spegeli Please Review this refactoring. This might conflict with your Customization, but make future changes easier.

**Comment by ParveenBhadooOfficial** [comment]
Deployed here: https://beta.bhadoomail.com/?adityabhambhu@bhadoo.net

**Comment by Spegeli** [comment]
Will take a look later or tomorrow.

**Comment by Spegeli** [comment]
One issue found:

https://www.postfach2go.de/?action=id&max@postfach2go.de

Will generate the email: actionidmax@postfach2go.de

The issue comes from:
```
        } elseif (!empty($this->query_string)) {
            return new DisplayEmailsPage($this->query_string, $this->config);
```
because the string is not empty so it use the complete string to generate the email.

**Comment by synox** [comment]
@Spegeli which link leads you to action=id? that should not happen.

**Comment by Spegeli** [comment]
no one links to action=id, this was only a example tat you can type any string and it will be converted in a email.

**Comment by synox** [comment]
Thanks for the feedback

**Pull request merged**
